import Link from "next/link";
import { CalendarDays, CheckCircle2, Clock3, DollarSign, LogOut, Scissors, Sparkles, UserRound } from "lucide-react";
import { format, isAfter, startOfDay } from "date-fns";
import { requireUser } from "@/lib/dal";
import { listBookings } from "@/lib/db";
import { LogoutButton, StatusSelect } from "@/components/dashboard-actions";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export default async function DashboardPage() {
  const user = await requireUser();
  const bookings = await listBookings(user);
  const upcoming = bookings.filter((item) => item.status === "confirmed" && isAfter(new Date(item.startTime), new Date())).slice(0, 6);
  const today = bookings.filter((item) => new Date(item.startTime) >= startOfDay(new Date()) && new Date(item.startTime).toDateString() === new Date().toDateString());
  const revenue = bookings.filter((item) => item.status === "completed").reduce((sum, item) => sum + item.priceCents, 0);
  const staffView = user.role !== "customer";
  return <main className="dashboard-page"><aside className="sidebar"><Link href="/" className="brand brand-light"><span className="brand-mark"><Scissors size={19} /></span><span>BREEZY <b>CUTS</b></span></Link><nav><Link className="active" href="/dashboard"><CalendarDays size={19} /> Overview</Link><Link href="/book"><Scissors size={19} /> New booking</Link><Link href="/"><UserRound size={19} /> Customer site</Link></nav><div className="sidebar-user"><div className="avatar avatar-dark">{user.name.split(" ").map((part) => part[0]).join("").slice(0, 2)}</div><div><b>{user.name}</b><span>{user.role}</span></div><LogoutButton><LogOut size={17} /></LogoutButton></div></aside><section className="dashboard-main"><header className="dashboard-header"><div><span>{format(new Date(), "EEEE, MMMM d")}</span><h1>{staffView ? "Shop overview" : `Hey, ${user.name.split(" ")[0]}.`}</h1></div><Link className="button button-primary" href="/book"><Scissors size={17} /> Book a cut</Link></header>
    <div className="metric-grid"><article><span className="metric-icon mint"><CalendarDays /></span><div><span>{staffView ? "Today's chairs" : "Upcoming"}</span><strong>{staffView ? today.length : upcoming.length}</strong><small>{staffView ? "appointments scheduled" : "confirmed appointments"}</small></div></article><article><span className="metric-icon yellow"><CheckCircle2 /></span><div><span>Completed</span><strong>{bookings.filter((b) => b.status === "completed").length}</strong><small>all-time services</small></div></article>{staffView ? <article><span className="metric-icon coral"><DollarSign /></span><div><span>Completed revenue</span><strong>{money.format(revenue / 100)}</strong><small>recorded services</small></div></article> : <article><span className="metric-icon coral"><Sparkles /></span><div><span>Fresh streak</span><strong>{bookings.filter((b) => b.status === "completed").length}</strong><small>cuts with Breezy</small></div></article>}</div>
    <section className="schedule-card"><div className="card-heading"><div><span className="kicker">UP NEXT</span><h2>{staffView ? "Upcoming appointments" : "Your appointments"}</h2></div><Link href="/book">Add booking</Link></div>{upcoming.length === 0 ? <div className="empty-state"><Clock3 size={30} /><h3>Nothing on the books yet.</h3><p>Pick a service and a time that fits your week.</p><Link className="button button-primary" href="/book">Book now</Link></div> : <div className="appointment-list">{upcoming.map((item) => <article key={item.id}><div className="date-tile"><b>{format(new Date(item.startTime), "d")}</b><span>{format(new Date(item.startTime), "MMM")}</span></div><div className="appointment-main"><strong>{item.serviceName}</strong><span>{format(new Date(item.startTime), "EEEE · h:mm a")} · {item.durationMinutes} min</span></div>{staffView && <div className="customer-cell"><b>{item.customerName}</b><span>{item.customerPhone}</span></div>}<div className="barber-cell"><div className="avatar">{item.barberName.split(" ").map((part) => part[0]).join("")}</div><span>{item.barberName}</span></div><b>{money.format(item.priceCents / 100)}</b>{staffView ? <StatusSelect bookingId={item.id} status={item.status} /> : <span className={`status ${item.status}`}>{item.status}</span>}</article>)}</div>}</section>
  </section></main>;
}
